package org.apache.cxf.jms_greeter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-25T00:20:01.406+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "JMSGreeterService", 
                  wsdlLocation = "file:/C:/java/cxf-queue/src/main/config/jms_greeter.wsdl",
                  targetNamespace = "http://cxf.apache.org/jms_greeter") 
public class JMSGreeterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.apache.org/jms_greeter", "JMSGreeterService");
    public final static QName GreeterPort = new QName("http://cxf.apache.org/jms_greeter", "GreeterPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/java/cxf-queue/src/main/config/jms_greeter.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JMSGreeterService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/java/cxf-queue/src/main/config/jms_greeter.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JMSGreeterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JMSGreeterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JMSGreeterService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JMSGreeterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JMSGreeterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JMSGreeterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JMSGreeterPortType
     */
    @WebEndpoint(name = "GreeterPort")
    public JMSGreeterPortType getGreeterPort() {
        return super.getPort(GreeterPort, JMSGreeterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JMSGreeterPortType
     */
    @WebEndpoint(name = "GreeterPort")
    public JMSGreeterPortType getGreeterPort(WebServiceFeature... features) {
        return super.getPort(GreeterPort, JMSGreeterPortType.class, features);
    }

}
