package org.apache.cxf.jms_greeter;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-25T00:20:01.341+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://cxf.apache.org/jms_greeter", name = "JMSGreeterPortType")
@XmlSeeAlso({org.apache.cxf.jms_greeter.types.ObjectFactory.class})
public interface JMSGreeterPortType {

    @WebMethod
    @RequestWrapper(localName = "greetMe", targetNamespace = "http://cxf.apache.org/jms_greeter/types", className = "org.apache.cxf.jms_greeter.types.GreetMe")
    @ResponseWrapper(localName = "greetMeResponse", targetNamespace = "http://cxf.apache.org/jms_greeter/types", className = "org.apache.cxf.jms_greeter.types.GreetMeResponse")
    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/jms_greeter/types")
    public java.lang.String greetMe(
        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/jms_greeter/types")
        java.lang.String requestType
    );

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", targetNamespace = "http://cxf.apache.org/jms_greeter/types", className = "org.apache.cxf.jms_greeter.types.GreetMeOneWay")
    public void greetMeOneWay(
        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/jms_greeter/types")
        java.lang.String requestType
    );

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.apache.org/jms_greeter/types", className = "org.apache.cxf.jms_greeter.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.apache.org/jms_greeter/types", className = "org.apache.cxf.jms_greeter.types.SayHiResponse")
    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/jms_greeter/types")
    public java.lang.String sayHi();
}
